import { Lender } from '../models';

export const MOCK_LENDERS: Lender[] = [
  {
    id: 'lnd-001', name: 'Taifa Capital', slug: 'taifa-capital', logo: '🏛️',
    description: 'Leading SME and personal lending institution serving Kenya since 2012.',
    minimum_interest_rate: 12.5, maximum_interest_rate: 24.0,
    minimum_loan_amount: 50000, maximum_loan_amount: 5000000,
    processing_time: '3-5 business days', acceptance_rate: 68.5,
    target_customer: 'SMEs & salaried professionals', risk_level: 'medium',
    trend_direction: 'down', trend_percentage: 0.35, active_offers: 4,
    contact_email: 'loans@taifacapital.co.ke', phone_number: '+254 700 111 001',
    physical_address: 'Westlands, Nairobi',
  },
  {
    id: 'lnd-002', name: 'Rafiki Microfinance', slug: 'rafiki-microfinance', logo: '🤝',
    description: 'Community-focused microfinance empowering small businesses across Kenya.',
    minimum_interest_rate: 15.0, maximum_interest_rate: 28.0,
    minimum_loan_amount: 10000, maximum_loan_amount: 500000,
    processing_time: '2-4 business days', acceptance_rate: 72.0,
    target_customer: 'Micro enterprises & groups', risk_level: 'low',
    trend_direction: 'stable', trend_percentage: 0, active_offers: 6,
    contact_email: 'apply@rafikimf.co.ke', phone_number: '+254 711 222 002',
    physical_address: 'Kenyatta Avenue, Nairobi',
  },
  {
    id: 'lnd-003', name: 'Horizon Lending Kenya', slug: 'horizon-lending', logo: '🌅',
    description: 'Premium asset-backed lending for property and vehicle financing.',
    minimum_interest_rate: 10.5, maximum_interest_rate: 18.5,
    minimum_loan_amount: 200000, maximum_loan_amount: 15000000,
    processing_time: '5-10 business days', acceptance_rate: 55.0,
    target_customer: 'Asset owners & professionals', risk_level: 'low',
    trend_direction: 'down', trend_percentage: 0.52, active_offers: 3,
    contact_email: 'credit@horizonlending.co.ke', phone_number: '+254 722 333 003',
    physical_address: 'Upper Hill, Nairobi',
  },
  {
    id: 'lnd-004', name: 'Mwangaza Finance', slug: 'mwangaza-finance', logo: '✨',
    description: 'Fast digital loans for salaried Kenyans with competitive rates.',
    minimum_interest_rate: 14.0, maximum_interest_rate: 26.0,
    minimum_loan_amount: 25000, maximum_loan_amount: 2000000,
    processing_time: '24-48 hours', acceptance_rate: 74.5,
    target_customer: 'Salaried employees', risk_level: 'medium',
    trend_direction: 'up', trend_percentage: 0.28, active_offers: 8,
    contact_email: 'hello@mwangazafinance.co.ke', phone_number: '+254 733 444 004',
    physical_address: 'Kilimani, Nairobi',
  },
  {
    id: 'lnd-005', name: 'SwiftPesa Credit', slug: 'swiftpesa-credit', logo: '⚡',
    description: 'Instant mobile-first credit solutions powered by digital underwriting.',
    minimum_interest_rate: 18.0, maximum_interest_rate: 32.0,
    minimum_loan_amount: 5000, maximum_loan_amount: 300000,
    processing_time: 'Same day', acceptance_rate: 81.0,
    target_customer: 'Mobile users & gig workers', risk_level: 'high',
    trend_direction: 'down', trend_percentage: 0.15, active_offers: 12,
    contact_email: 'support@swiftpesa.co.ke', phone_number: '+254 744 555 005',
    physical_address: 'Westlands, Nairobi',
  },
  {
    id: 'lnd-006', name: 'Kifaru SACCO Loans', slug: 'kifaru-sacco', logo: '🦏',
    description: 'Member-owned SACCO offering affordable cooperative lending.',
    minimum_interest_rate: 11.0, maximum_interest_rate: 16.5,
    minimum_loan_amount: 30000, maximum_loan_amount: 3000000,
    processing_time: '4-7 business days', acceptance_rate: 62.0,
    target_customer: 'SACCO members', risk_level: 'low',
    trend_direction: 'stable', trend_percentage: 0, active_offers: 5,
    contact_email: 'loans@kifarusacco.co.ke', phone_number: '+254 755 666 006',
    physical_address: 'Thika Road, Nairobi',
  },
  {
    id: 'lnd-007', name: 'Jenga SME Capital', slug: 'jenga-sme', logo: '🏗️',
    description: 'Growth capital for Kenyan SMEs with flexible repayment structures.',
    minimum_interest_rate: 13.5, maximum_interest_rate: 22.0,
    minimum_loan_amount: 100000, maximum_loan_amount: 10000000,
    processing_time: '5-8 business days', acceptance_rate: 58.0,
    target_customer: 'Growing SMEs', risk_level: 'medium',
    trend_direction: 'down', trend_percentage: 0.41, active_offers: 7,
    contact_email: 'funding@jengasme.co.ke', phone_number: '+254 766 777 007',
    physical_address: 'Industrial Area, Nairobi',
  },
  {
    id: 'lnd-008', name: 'Elite Asset Finance', slug: 'elite-asset', logo: '💎',
    description: 'High-value asset financing for vehicles, equipment, and machinery.',
    minimum_interest_rate: 9.5, maximum_interest_rate: 15.0,
    minimum_loan_amount: 500000, maximum_loan_amount: 25000000,
    processing_time: '7-14 business days', acceptance_rate: 48.0,
    target_customer: 'Corporates & HNW individuals', risk_level: 'low',
    trend_direction: 'down', trend_percentage: 0.62, active_offers: 2,
    contact_email: 'assets@elitefinance.co.ke', phone_number: '+254 777 888 008',
    physical_address: 'Karen, Nairobi',
  },
  {
    id: 'lnd-009', name: 'MobiCash Africa', slug: 'mobicash-africa', logo: '📱',
    description: 'M-Pesa integrated micro-loans for everyday financial needs.',
    minimum_interest_rate: 20.0, maximum_interest_rate: 35.0,
    minimum_loan_amount: 1000, maximum_loan_amount: 150000,
    processing_time: 'Instant', acceptance_rate: 85.0,
    target_customer: 'Mobile money users', risk_level: 'high',
    trend_direction: 'up', trend_percentage: 0.45, active_offers: 15,
    contact_email: 'care@mobicash.africa', phone_number: '+254 788 999 009',
    physical_address: 'CBD, Nairobi',
  },
  {
    id: 'lnd-010', name: 'Ndovu Credit Union', slug: 'ndovu-credit', logo: '🐘',
    description: 'Trusted credit union serving civil servants and parastatals.',
    minimum_interest_rate: 10.0, maximum_interest_rate: 14.5,
    minimum_loan_amount: 50000, maximum_loan_amount: 5000000,
    processing_time: '3-6 business days', acceptance_rate: 65.0,
    target_customer: 'Civil servants', risk_level: 'low',
    trend_direction: 'stable', trend_percentage: 0, active_offers: 4,
    contact_email: 'loans@ndovucredit.co.ke', phone_number: '+254 799 000 010',
    physical_address: 'Haile Selassie Ave, Nairobi',
  },
  {
    id: 'lnd-011', name: 'Savanna Growth Fund', slug: 'savanna-growth', logo: '🌾',
    description: 'Agricultural and agribusiness lending across Rift Valley and Western Kenya.',
    minimum_interest_rate: 12.0, maximum_interest_rate: 20.0,
    minimum_loan_amount: 75000, maximum_loan_amount: 8000000,
    processing_time: '6-10 business days', acceptance_rate: 52.0,
    target_customer: 'Farmers & agribusiness', risk_level: 'medium',
    trend_direction: 'down', trend_percentage: 0.38, active_offers: 3,
    contact_email: 'agri@savannagrowth.co.ke', phone_number: '+254 700 121 011',
    physical_address: 'Nakuru Town',
  },
  {
    id: 'lnd-012', name: 'Coastline Finance', slug: 'coastline-finance', logo: '🌊',
    description: 'Coastal region specialist in tourism and hospitality sector loans.',
    minimum_interest_rate: 14.5, maximum_interest_rate: 25.0,
    minimum_loan_amount: 40000, maximum_loan_amount: 4000000,
    processing_time: '4-6 business days', acceptance_rate: 60.0,
    target_customer: 'Tourism & hospitality', risk_level: 'medium',
    trend_direction: 'up', trend_percentage: 0.22, active_offers: 5,
    contact_email: 'info@coastlinefinance.co.ke', phone_number: '+254 711 232 012',
    physical_address: 'Mombasa Road, Mombasa',
  },
  {
    id: 'lnd-013', name: 'Ubuntu Capital', slug: 'ubuntu-capital', logo: '🌍',
    description: 'Social impact lending for women entrepreneurs and youth startups.',
    minimum_interest_rate: 13.0, maximum_interest_rate: 21.0,
    minimum_loan_amount: 20000, maximum_loan_amount: 2000000,
    processing_time: '3-5 business days', acceptance_rate: 70.0,
    target_customer: 'Women & youth entrepreneurs', risk_level: 'medium',
    trend_direction: 'down', trend_percentage: 0.19, active_offers: 6,
    contact_email: 'impact@ubuntucapital.co.ke', phone_number: '+254 722 343 013',
    physical_address: 'Ngong Road, Nairobi',
  },
  {
    id: 'lnd-014', name: 'Pinnacle Bank Loans', slug: 'pinnacle-bank-loans', logo: '🏦',
    description: 'Bank-grade personal and mortgage products with competitive APR.',
    minimum_interest_rate: 8.5, maximum_interest_rate: 14.0,
    minimum_loan_amount: 500000, maximum_loan_amount: 50000000,
    processing_time: '10-21 business days', acceptance_rate: 45.0,
    target_customer: 'Prime borrowers', risk_level: 'low',
    trend_direction: 'down', trend_percentage: 0.55, active_offers: 2,
    contact_email: 'mortgages@pinnaclebank.co.ke', phone_number: '+254 733 454 014',
    physical_address: 'Chiromo Road, Nairobi',
  },
  {
    id: 'lnd-015', name: 'Kazi Yetu Lending', slug: 'kazi-yetu', logo: '💼',
    description: 'Employment-linked loans for formal sector workers with payroll deduction.',
    minimum_interest_rate: 11.5, maximum_interest_rate: 19.0,
    minimum_loan_amount: 30000, maximum_loan_amount: 2500000,
    processing_time: '2-3 business days', acceptance_rate: 76.0,
    target_customer: 'Formal sector employees', risk_level: 'low',
    trend_direction: 'stable', trend_percentage: 0, active_offers: 9,
    contact_email: 'loans@kaziyetu.co.ke', phone_number: '+254 744 565 015',
    physical_address: 'Tom Mboya Street, Nairobi',
  },
  {
    id: 'lnd-016', name: 'Heritage Trust Finance', slug: 'heritage-trust', logo: '🏠',
    description: 'Family and diaspora remittance-backed lending solutions.',
    minimum_interest_rate: 12.5, maximum_interest_rate: 23.0,
    minimum_loan_amount: 25000, maximum_loan_amount: 3500000,
    processing_time: '4-8 business days', acceptance_rate: 63.0,
    target_customer: 'Diaspora families', risk_level: 'medium',
    trend_direction: 'up', trend_percentage: 0.31, active_offers: 4,
    contact_email: 'trust@heritagefinance.co.ke', phone_number: '+254 755 676 016',
    physical_address: 'Parklands, Nairobi',
  },
];
